name: update workflow
on: workflow_dispatch
push:
  branches: [main]

jobs:
  deploy: 
    name: Deploy
    runs-on: ubuntu-latest
    steps:
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
              cd CMSC389T-Web-Template
              git pull